GET http://localhost:5002/users

###

GET http://localhost:5002/users/64287d167287273b4bfcd995

###

POST http://localhost:5002/users
Content-Type: application/json

{
    "firstName": "asd",
    "lastName": "test",
    "age": 29
}

###

DELETE http://localhost:5002/users/64287d167287273b4bfcd995

###

PATCH http://localhost:5002/users/64287d2c7287273b4bfcd998
Content-Type: application/json

{"firstName": "LOLLO"}