GET http://localhost:5002/users

###

GET http://localhost:5002/users/64289ab37680b0b8d8b2d5a6

###

GET http://localhost:5002/users/test

###
POST http://localhost:5002/users
Content-Type: application/json

{
    "firstName": "Nicolo",
    "lastName": "Junior",
    "age": 21
}

###

DELETE http://localhost:5002/users/6454f3329d2af107136b4226

###

PATCH http://localhost:5002/users/642acd6220240d6d0a008d57
Content-Type: application/json

{"lastName": "Piccolo"}